import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { IoMdArrowBack } from "react-icons/io";
import { MdOutlineLightMode } from "react-icons/md";
import { Toaster } from "react-hot-toast";
import ContactList from "../components/ContactList";
import Navbar from "../components/Navbar";
import { fetchContactLists } from "../utils/fetchContactLists";
import { ContactListProps } from "../typings";
import { useState } from "react";

interface Props {
  contactLists: ContactListProps[];
}

export default function Home({ contactLists }: Props) {
  const [contactListDatas, setContactListDatas] = useState(contactLists);
  console.log(contactLists);
  return (
    <div className="container">
      <Head>
        <title>Contact list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Toaster />
        <div className="contact-wrapper">
          <div className="left-sidebar">
            <div className="left-top"></div>
            <div className="left-center">
              <IoMdArrowBack />
            </div>
            <div className="left-bottom"></div>
          </div>
          <div className="main-content">
            <div className="main-top"></div>
            <div className="main-center">
              <Navbar setContactListDatas={setContactListDatas} />
            </div>
            <div className="main-bottom">
              <div className="contact-list-container">
                {contactListDatas?.map((contactList: ContactListProps) => (
                  <ContactList
                    key={contactList._id}
                    contactList={contactList}
                    setContactListDatas={setContactListDatas}
                  />
                ))}
              </div>
            </div>
          </div>
          <div className="right-sidebar">
            <div className="right-top"></div>
            <div className="right-center">
              <MdOutlineLightMode />
            </div>
            <div className="right-bottom"></div>
          </div>
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const contactLists = await fetchContactLists();
  return {
    props: {
      contactLists,
    },
  };
};
